### ISSUE TITLE
global name 'nvmlDeviceGetEnforcedPowerLimit' is not defined

### ISSUE THREAD

**Issue by JesperNaarttijarvi** [m4rkw/gpustatd#4]
Getting error after fresh install.

**Trace**
File ".../gpustatd/nvidia.py", line 91, in refresh
`self.devices[device_id]['limit_f']` = 
         `nvmlDeviceGetPowerManagementLimit(self.handles[device_id])/1000`
NameError: global name 'nvmlDeviceGetEnforcedPowerLimit' is not defined

**Comment by JesperNaarttijarvi** [comment]
It seems like the `self.devices[device_id]['limit_f'] =
nvmlDeviceGetPowerManagementLimit(self.handles[device_id])/1000` has nothing to do with nvmlDeviceGetEnforcedPowerLimit. It get the same error with this changed aswell.

**Comment by gordan-bobic** [comment]
What GPU is it? Does it support power limit getting/setting?
What do you get from nvidia-smi?

**Comment by JesperNaarttijarvi** [comment]
Tried with both 1060 6gb and 970 gtx. 

Will do a new clone and see what happens

**Comment by JesperNaarttijarvi** [comment]
After reinstalling PyYAML and gpustatd, the error seems to be gone.
