### ISSUE TITLE
dial back overclock and power limit at high temps

### ISSUE THREAD

**Issue by m4rkw** [m4rkw/gpustatd#8]
the dial-back built into minotaur that dials back the power limit should be moved into gpustatd

also i think it should dial the overclock offsets slowly back to 0 if the temp exceeds the configured limit

**Comment by m4rkw** [comment]
setting of oc and power limit should be done in gpustatd, with minotaur requesting the change via state files.

**Comment by gordan-bobic** [comment]
This is what the following is for:

regulate_card_temperatures: true
card_temperature_limit: 80

and it does it in a much better way.

I disagree on moving clock setting out of minotaur, clock setting should be as tightly coupled and to minotaur and as sequential and synchronous as possible.

**Comment by m4rkw** [comment]
ok i concede on clock settings, i think power limit throttling would be safer being in gpustatd though

**Comment by gordan-bobic** [comment]
Agreed, best place for power limit throttling is in gpustatd.
