### ISSUE TITLE
Implausible fan speed

### ISSUE THREAD

**Issue by gordan-bobic** [m4rkw/gpustatd#9]
Not sure if this still happens, but it is present in fanotaur 0.8.5

```
2018-02-15 21:00:23: [warning] implausible fan speed: 0 %
```

It keeps re-self-testing while the card happily overheats.

**Comment by m4rkw** [comment]
it also continuously tries to increase the fan speed

````
    if current_fan_speed == 0:
      Log().add('warning', 'implausible fan speed: %d %%' % (current_fan_speed))

    if current_fan_speed != fan_speed:
      Nvidia().set_fan_speed(device_id, fan_speed)
````

so something isn't allowing it to set it

**Comment by gordan-bobic** [comment]
I think I know what it is - one card missing. Xorg and CUDA device IDs need fixing.
